# The URL the site will be built for
base_url = "https://knz.ai"
title = "Kenzi Connor"
author = "Kenzi Connor"
description = "Staff Software Engineer - VP Engineering - Director of Engineering - CEO & CTO"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
highlight_code = true

[extra]
color_theme = "theme-base-08"
sidebar_reverse = true
sidebar_links = [
    {url = "https://github.com/knzai", name = "GitHub"},
    {url = "https://www.linkedin.com/in/knzai/", name = "LinkedIn"},
    {url = "mailto:site@knz.ai", name = "site@knz.ai"},
    {url = "https://tech.lgbt/@knzai", name = "Mastadon"},
]
sidebar_sticky = true